# TODO
# Brauche noch Funktion, um Datum explizit zu numeric umzuwandeln!
# Diese braucht nicht exportiert zu werden, interne Funktion reicht, die dann in `check_sequence` verwendet wird.
#
# Das combn passt eigentlich viel besser in die sgn Funktionen, wo ich gerade die Dokumentation mir ausdenke
#
# Dokumentaiton von sgn anpassen, bzw. den Text der Description und Details hinuzfügen & Formel als Inline Code formatieren
#
# Quellen hinzufügen (Buch von Kendall)


#' Calculate sum of signs of two vectors
#'
#' @description
#' Der folgende Satz stimmt zwar aktuell, Funktionsweise soll
#' aber geändert werden
#' This function takes two matrices as input (generated by combn) and returns
#' the summed product of the form \code{sign(z2 - z1) * sign(t2 - t2)}.
#'
#' @param t A vector of ranks.
#' @param z A vector of ranks.
#'
#' @return An Integer
#' @export
#' 
#' @references Kendall der olle Hengst
#'
#' @seealso \code{\link{onesided_sgn}}
#' @examples
sgn <- function(t, z) {
	sum(
		purrr::pmap_dbl(list(t[, 2], t[, 1], z[, 2], z[, 1]),
						~ sign(..1 - ..2) * sign(..3 - ..4)
		)
	)
}

#' Calculate sum of signs of one vector
#' 
#' @description 
#' This fuction takes a vector of ranks as 
#' input and returns the summed product of
#' the signs of \eqn{\binom {n} {2}} permutations.
#' 
#' @param t A vector of ranks.
#'
#' @return An Integer
#' @export
#' 
#' @details
#' \code{onesided_sgn} operates like \code{\link{sgn}} but takes only 
#' a single vector as input. In the context of the Kendall's Rank Correlation
#' Coefficient this assumes, that the provided vector represents entries in 
#' their natural order.
#'
#' @seealso \code{\link{sgn}}
#' @examples
onesided_sgn <- function(t) {
	sum(
		purrr::map2_dbl(t[, 2], t[, 1]), function(t2, t1) sign(t2 - t1)
	)
}


#' Title
#'
#' @param t 
#' @param n 
#'
#' @return
check_sequence <- function(t = NULL, n) {
	if (!is.null(t)) {
		if (length(t) != n) {
			stop("While t was supplied: objects t and Y are not of same length.")
		}
		return(t)
	}
	seq(from = 1, to = n)
}

# nicht exporieren
coerce_to_num <- function(x) {

}
